M48
; DRILL file {KiCad (6.0.9)} date Wed Dec  7 15:22:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-07T15:22:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.4055Y-2.4861
X4.4055Y-4.9581
X8.0575Y-2.4861
X8.0575Y-4.9581
T0
M30
